In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("DT-Credit.csv")
df

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
398,37.728,2525,192,1,44,13,No,No,Yes,South,0
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Income     400 non-null    float64
 1   Limit      400 non-null    int64
 2   Rating     400 non-null    int64
 3   Cards      400 non-null    int64
 4   Age        400 non-null    int64
 5   Education  400 non-null    int64
 6   Own        400 non-null    object
 7   Student    400 non-null    object
 8   Married    400 non-null    object
 9   Region     400 non-null    object
 10  Balance    400 non-null    int64
dtypes: float64(1), int64(6), object(4)
memory usage: 34.5+ KB

In [4]:
df = df.drop(columns=['Income',	'Limit',	'Rating',	'Cards',	'Age',	'Education'])
df

     Own Student Married Region  Balance
0     No      No     Yes  South      333
1    Yes     Yes     Yes   West      903
2     No      No      No   West      580
3    Yes      No      No   West      964
4     No      No     Yes  South      331
..   ...     ...     ...    ...      ...
395   No      No     Yes  South      560
396   No      No      No   East      480
397  Yes      No     Yes  South      138
398   No      No     Yes  South        0
399  Yes      No      No   West      966

[400 rows x 5 columns]

In [5]:
df.isnull()

       Own  Student  Married  Region  Balance
0    False    False    False   False    False
1    False    False    False   False    False
2    False    False    False   False    False
3    False    False    False   False    False
4    False    False    False   False    False
..     ...      ...      ...     ...      ...
395  False    False    False   False    False
396  False    False    False   False    False
397  False    False    False   False    False
398  False    False    False   False    False
399  False    False    False   False    False

[400 rows x 5 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder

# Copy the original DataFrame
df_new = df.copy()

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Apply Label Encoding to each specified column
for column in ['Own',	'Student',	'Married',	'Region',	'Balance']:
    df_new[column] = label_encoder.fit_transform(df_new[column])

df_new

     Own  Student  Married  Region  Balance
0      0        0        1       1       67
1      1        1        1       2      196
2      0        0        0       2      126
3      1        0        0       2      210
4      0        0        1       1       66
..   ...      ...      ...     ...      ...
395    0        0        1       1      120
396    0        0        0       0      103
397    1        0        1       1       25
398    0        0        1       1        0
399    1        0        0       2      211

[400 rows x 5 columns]

In [7]:
df_new.columns

Index(['Own', 'Student', 'Married', 'Region', 'Balance'], dtype='object')

In [8]:
df_new = (df_new-df_new.min())/(df_new.max()-df_new.min())
df_new

     Own  Student  Married  Region   Balance
0    0.0      0.0      1.0     0.5  0.236749
1    1.0      1.0      1.0     1.0  0.692580
2    0.0      0.0      0.0     1.0  0.445230
3    1.0      0.0      0.0     1.0  0.742049
4    0.0      0.0      1.0     0.5  0.233216
..   ...      ...      ...     ...       ...
395  0.0      0.0      1.0     0.5  0.424028
396  0.0      0.0      0.0     0.0  0.363958
397  1.0      0.0      1.0     0.5  0.088339
398  0.0      0.0      1.0     0.5  0.000000
399  1.0      0.0      0.0     1.0  0.745583

[400 rows x 5 columns]

In [9]:
y = df_new['Balance']
X = df_new.drop(columns=['Balance'])

Yarr = y.to_numpy()
Xarr = X.to_numpy()

print("Shape of Y:", Yarr.shape)
print("Shape of X:", Xarr.shape)

Shape of Y: (400,)
Shape of X: (400, 4)

In [10]:
import numpy as np

def shuffle_and_split_data(X, Y, test_ratio, val_ratio):
    # Shuffle indices
    shuffled_indices = np.random.permutation(len(X))
    
    # Calculate the sizes for test and validation sets
    test_set_size = int(len(X) * test_ratio)
    val_set_size = int(len(X) * val_ratio)
    
    # Get indices for each set
    test_indices = shuffled_indices[:test_set_size]
    val_indices = shuffled_indices[test_set_size:test_set_size + val_set_size]
    train_indices = shuffled_indices[test_set_size + val_set_size:]
    
    # Split the data
    return (X[train_indices], X[val_indices], X[test_indices], 
            Y[train_indices], Y[val_indices], Y[test_indices])

In [11]:
Xtrain_set, Xval_set, Xtest_set, Ytrain_set, Yval_set, Ytest_set = shuffle_and_split_data(Xarr, Yarr, test_ratio=0.15, val_ratio=0.15)

In [12]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor ,plot_tree
import matplotlib.pyplot as plt

In [13]:
clf = DecisionTreeRegressor(max_depth=5,random_state=42)

In [14]:
clf.fit(Xtrain_set,Ytrain_set)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [15]:
y_val_pred = clf.predict(Xval_set)
y_test_pred = clf.predict(Xtest_set)

In [16]:
def calculate_mse(y_true, y_pred):
    n = len(y_true)
    mse = sum((y_t - y_p) ** 2 for y_t, y_p in zip(y_true, y_pred)) / n
    return mse
    
mse1 = calculate_mse(Yval_set, y_val_pred)
print("Mean Squared Error:", mse1)

Mean Squared Error: 0.09925171747231103

In [17]:
mse2 = calculate_mse(Ytest_set, y_test_pred)
print("Mean Squared Error:", mse2)

Mean Squared Error: 0.1081210626854748

In [18]:
from xgboost import XGBRegressor
model = XGBRegressor()

model.fit(Xtrain_set, Ytrain_set)
y_train_pred_xgb = model.predict(Xtrain_set)
y_val_pred_xgb = model.predict(Xval_set)
y_test_xgb = model.predict(Xtest_set)

In [19]:
mse3 = calculate_mse(Ytrain_set, y_train_pred_xgb)
print("Mean Squared Error:", mse3)

Mean Squared Error: 0.09318143468965448

In [20]:
mse4 = calculate_mse(Yval_set, y_val_pred_xgb)
print("Mean Squared Error:", mse4)

Mean Squared Error: 0.09921884346239516

In [21]:
mse5 = calculate_mse(Ytest_set, y_test_xgb)
print("Mean Squared Error:", mse5)

Mean Squared Error: 0.10808402400072044